### ISSUE TITLE
Carryover dates are not shown

### ISSUE THREAD

**Issue by flexwie** [fosscom/kalle#1]
Dates at the end of the month that are not fitting in the fixed grid are skipped and only shown grayed out on the next month

e6f88816281eac163daf1cea0fbe219d27be6be0

**Comment by marioreggiori** [comment]
Should 6 rows be displayed by default or only when necessary?

**Comment by flexwie** [comment]
I prefer a dynmic row count. We can smooth out transitions with some animations.
